Repository JUNOSHON/next-seminar-blog, pull requests merged in 2024-01, with the labels that each got.

#24 [Feat] 이전포스트, 다음포스트 기능 구현
  src/app/components/AdjacentPostCard.tsx
  src/app/components/PostContent.tsx
  src/app/posts/[slug]/page.tsx
  src/app/service/posts.ts
Labels: feature

#28 [Feat] nodemailer 이메일 전송기능 구현
  package.json
  src/app/api/contact/route.ts
  src/app/components/ContactForm.tsx
  src/app/contact/page.tsx
  src/app/service/contact.ts
  src/app/service/email.ts
  yarn.lock
Labels: feature

#31 [Refactor] SEO 최적화
  src/app/about/page.tsx
  src/app/contact/page.tsx
  src/app/favicon.ico
  src/app/layout.tsx
  src/app/posts/[slug]/page.tsx
  src/app/posts/page.tsx
Labels: refactor

#32 [Fix] React Markdown 컴포넌트 수정
  src/app/components/MarkdownViewer.tsx
Labels: bug

#35 [Feat] workflow 설정
  .github/workflows/vercel-deploy.yaml
Labels: CI/CD

#36 마크다운 뷰어 적용#33
  next.config.js
  package.json
  src/app/posts/[slug]/page.tsx
  tailwind.config.ts
  yarn.lock
Labels: feature
